name: Lua Check

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  luacheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install luacheck
        run: sudo apt-get update && sudo apt-get install -y lua-check
      - name: Run luacheck
        run: |
          git ls-files '*.lua' | xargs -r luacheck --globals vim --no-max-line-length
