name: Lua Check

on:
  pull_request:

jobs:
  luacheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install luacheck
        run: sudo apt-get update && sudo apt-get install -y lua-check
      - name: Run luacheck
        run: |
          git ls-files '*.lua' | xargs -r luacheck --globals vim --no-max-line-length
